### ISSUE TITLE
OAuth -Connection to MSCRM to Ping Dynamics 365 from VSTS Agent failing

### ISSUE THREAD

**Issue by sanjay1913** [WaelHamze/xrm-ci-framework#198] opened 2019-02-27 15:53 UTC
Dear Wael @WaelHamze 

Please help , I am using Dynamics 365 Sandbox and trying to connect using OAuth for a user ABC in our company ABCDomain with AppId in Azure but failing. The same connection works with .NET code (using Microsoft.Xrm.Tooling.Connector;) from local machine 

[section]Starting: Inline Powershell
============
Task         : Run Inline Powershell
Description  : Run the Powershell from a textbox
Version      : 1.1.7
Author       : Peter Groenewegen - Xpirit
Hello world AuthType=OAuth;Url=https://OrgName.crm4.dynamics.com;Username=ABC@ABCDomain.onmicrosoft.com;Password=***;AppId=gfdd252f-97d9-477d-a4c3-01480a672c6d;RedirectUri=http://localhost/;LoginPrompt=Auto;
[section]Finishing: Inline Powershell

[section]Starting: MSCRM CRM Ping OAuth
============
Task         : MSCRM Ping
Description  : A sample task that checks connectivity to a Dynamics 365 environment
Version      : 10.0.5
Author       : Wael Hamze
Help         : Performs a WhoAmIRequest against the target CRM environment
======
[error]Organization cannot be null or empty.
Parameter name: Organization Name
[section]Finishing: MSCRM CRM Ping OAuth

O365 connection went well
---------------------------------
It works with O365 (connection) connectivity with Hosted Agent and Private Agent
AuthType=Office365;Url=https://CRM334ada55.crm4.dynamics.com;Username=admin@CRM334ada55.onmicrosoft.com;Password=sss@Cggg34ada55

**Comment by sanjay1913** [comment] 2019-03-15 15:56
Hi Wael, @WaelHamze  

Can you please suggest ?

Thank you
Sanjay

**Comment by WaelHamze** [comment] 2019-03-24 17:27
@sanjay1913 Do you get any login prompts when running from .NET?

Any reason why you can't use the username/password?

**Comment by majakubowski** [comment] 2019-03-26 08:53
@WaelHamze @sanjay1913 I have similar bug.. and I found the bug - PR is on my way ;)

**Comment by sanjay1913** [comment] 2019-03-27 14:01
@majakubowski , Please help on this What was the connection string and how it got resolved?

**Comment by sanjay1913** [comment] 2019-03-27 14:18
> @sanjay1913 Do you get any login prompts when running from .NET?
> [Sanjay : No do not prompts login when run .NET]
> Any reason why you can't use the username/password? .
[ Sanjay : I am able to pass user ID and password  for both .NET code where connection is working also .ping.ps1 where have failed for both O356 and OAuth authentication.  
Is this always that org name AABTCS and user under the domain @AABTCS.onmicrosoft.com got registered should be same like in case of trail version  , Are we expecting users in such format ? Here in our case users are from different domain.  Not sure what is happening here .

> @sanjay1913 Do you get any login prompts when running from .NET?
> 
> Any reason why you can't use the username/password?

Hi Wael @WaelHamze 

I am able to connect from Hosted /Private agent pool to Trail version with connection string O365 connectionString="AuthType=Office365;Url=https://AABTCS.crm4.dynamics.com;Username=USERAAB@AABTCS.onmicrosoft.com;Password=MOON@2019"

I am trying to connect from our Private Agent to Sandbox with O365 and OAuth then both failing . 
O365 : Connection String 
connectionString="AuthType=OAuth;Url=https://dev-1.crm4.dynamics.com;Username=UserDev@mycompany.onmicrosoft.com;Password=******;AppId=gdfd252f-97d9-477d-a4c3-01480a672c6c;RedirectUri=http://localhost/;LoginPrompt=Auto;"

connectionString="AuthType=Office365;Url=https://dev-1.crm4.dynamics.com/;Username=UserDev@mycompany.onmicrosoft.com;Password=*****;"

Both are failing . Error message is below for O365:
##[warning]Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
##[warning]Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
##[debug]Connecting to CRM [attempt 2]
##[warning]Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
##[warning]Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
##[debug]Connecting to CRM [attempt 3]
##[warning]Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
##[warning]Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=warning]Unable to Login to Dynamics CRM
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Select-WhoAmI : Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM
##[debug]Unable to Login to Dynamics CRM
##[debug]At C:\DATA\Agent\_work\tools\MSCRMBuildTools\9.0.11\xRMCIFramework\9.0.0\Ping.ps1:26 char:18
##[debug]+ ... utingUser = Select-WhoAmI -ConnectionString $CrmConnectionString -Ver ...
##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Select-WhoAmI], Exception
##[debug]    + FullyQualifiedErrorId : System.Exception,Xrm.Framework.CI.PowerShell.Cmdlets.SelectXrmWhoAmICommand
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, C:\DATA\Agent\_work\tools\MSCRMBuildTools\9.0.11\xRMCIFramework\9.0.0\Ping.ps1: line 26
##[debug]at <ScriptBlock>, C:\DATA\Agent\_work\_tasks\MSCRMPing_d8587a60-cd25-11e6-a324-f3fd298c325e\10.0.5\MSCRMPing.ps1: line 28
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Exception: Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM
##[debug]Unable to Login to Dynamics CRM
##[debug]   at Xrm.Framework.CI.Common.XrmConnectionManager.ConnectToCRM(String connectionString, Int32 timeout)
##[debug]   at Xrm.Framework.CI.PowerShell.Cmdlets.XrmCommandBase.BeginProcessing()
##[debug]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.DoBegin()
##[error]Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.logissue type=error]Couldn't connect to CRM instance after 3 attempts: Unable to Login to Dynamics CRM%0D%0AUnable to Login to Dynamics CRM
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: MSCRM CRM Ping OAuth Office365

**Comment by majakubowski** [comment] 2019-03-27 17:33
Problem was in XrmManager - when using OAuth authentication then CrmServiceClient create OrganizationWebProxyClient instead OrganizationServiceProxy... but regardless of the type of authentication, timeout was always set on OrganizationServiceProxy.

I use xrm-ci-framework with few onprem environments with connection string: AuthType=OAuth;Username=username@domain.local; Password=somestrongpassword;Url=http://somelocalurl.domain.local;AppId=2ad88395-b77d-4561-9441-d0e40824f9bc;RedirectUri=app://5d3e90d6-aa8e-48a8-8f2c-58b45cc67315/;TokenCacheStorePath =.\oauthtoken.cache;LoginPrompt=Never

**Comment by sanjay1913** [comment] 2019-03-29 16:38
@majakubowski  : Got query 

1.  Is this Query will be same for D365 online ?
AuthType=OAuth;Username=username@domain.local; Password=somestrongpassword;Url=http://somelocalurl.domain.local;AppId=2ad88395-b77d-4561-9441-d0e40824f9bc;RedirectUri=app://5d3e90d6-aa8e-48a8-8f2c-58b45cc67315/;TokenCacheStorePath =.\oauthtoken.cache;LoginPrompt=Never


2.  I downloaded XRM 9.0 , Do You have all latest files working for you ,  Is that in GitHub ?  Is this path ? How to compile ? Is this updated i VSTS tasks online ? 

https://github.com/WaelHamze/xrm-ci-framework/tree/master/MSDYNV9/Xrm.Framework.CI
fix for connection using oauth / OrganizationWebProxyClient #204

@WaelHamze  Could you please share the working tasks in VSTS so that We can use .

**Comment by majakubowski** [comment] 2019-03-29 21:00
@sanjay1913 it's path / PR (pull request).. It's works for me with onpremises & online, but with a named user (with real username & password). I'm unable to prepare connection string that works with CrmServiceClient and application user / app registration. You mention that you have a working .NET code - can you share the code that creates the connection.

**Comment by sanjay1913** [comment] 2019-04-01 09:15
> @sanjay1913 it's path / PR (pull request).. It's works for me with onpremises & online, but with a named user (with real username & password). I'm unable to prepare connection string that works with CrmServiceClient and application user / app registration. You mention that you have a working .NET code - can you share the code that creates the connection.

@majakubowski 

Please find below code for .NET .



App config.

 <add name="MyCRMServer" connectionString="AuthType=OAuth;Url=https://AbcMydev.crm4.dynamics.com;Username=User1@contosa.onmicrosoft.com;Password=[];AppId=gdfd252f-97d9-477d-23a-01480a672c6c;RedirectUri=http://localhost/;LoginPrompt=Auto;TokenCacheStorePath =c:\\MyTokenCache"/>

Program.cs 
--------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using Microsoft.Xrm.Tooling.Connector;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Linq;
using System.ServiceModel.Description;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Management.Authorization;

namespace ConnectToDynamics365Online
{
    class Program
    {
        static void Main(string[] args)
        {
            string ConnectionString = ConfigurationManager.ConnectionStrings[1].ConnectionString;
           
            CrmServiceClient conn = new Microsoft.Xrm.Tooling.Connector.CrmServiceClient(ConnectionString);
            if (conn.IsReady)
            {
                Console.WriteLine(conn.GetMyCrmUserId());
            }
            else
            {
                Console.WriteLine(conn.LastCrmError);
            }
        } 
   }
}

**Comment by sanjay1913** [comment] 2019-04-01 09:17
> @sanjay1913 it's path / PR (pull request).. It's works for me with onpremises & online, but with a named user (with real username & password). I'm unable to prepare connection string that works with CrmServiceClient and application user / app registration. You mention that you have a working .NET code - can you share the code that creates the connection.



> > @sanjay1913 it's path / PR (pull request).. It's works for me with onpremises & online, but with a named user (with real username & password). I'm unable to prepare connection string that works with CrmServiceClient and application user / app registration. You mention that you have a working .NET code - can you share the code that creates the connection.
> 
> @majakubowski
> 
> Please find below code for .NET .
> App config.
> ## Program.cs
> using Microsoft.Xrm.Sdk;
> using Microsoft.Xrm.Sdk.Client;
> using Microsoft.Xrm.Tooling.Connector;
> using System;
> using System.Collections.Generic;
> using System.Collections.ObjectModel;
> using System.Configuration;
> using System.Linq;
> using System.ServiceModel.Description;
> using System.Text;
> using System.Threading.Tasks;
> using Microsoft.Azure.Management.Authorization;
> 
> namespace ConnectToDynamics365Online
> {
> class Program
> {
> static void Main(string[] args)
> {
> string ConnectionString = ConfigurationManager.ConnectionStrings[1].ConnectionString;
> 
> ```
>         CrmServiceClient conn = new Microsoft.Xrm.Tooling.Connector.CrmServiceClient(ConnectionString);
>         if (conn.IsReady)
>         {
>             Console.WriteLine(conn.GetMyCrmUserId());
>         }
>         else
>         {
>             Console.WriteLine(conn.LastCrmError);
>         }
>     } 
> ```
> }
> }


 <add name="MyCRMServer" connectionString="AuthType=OAuth;Url=https://AbcMydev.crm4.dynamics.com;Username=User1@contosa.onmicrosoft.com;Password=[];AppId=gdfd252f-97d9-477d-23a-01480a672c6c;RedirectUri=http://localhost/;LoginPrompt=Auto;TokenCacheStorePath =c:\\MyTokenCache"/>

**Comment by sanjay1913** [comment] 2019-04-01 16:06
Hi @WaelHamze  and @majakubowski 
https://github.com/WaelHamze/xrm-ci-framework/tree/master/MSDYNV9/Xrm.Framework.CI 
I have downloaded it but could not able to compile it. Can you please share the compiled one? I am using powershell ping.ps1 codes . Is this got updated in VSTS tasks as well?

**Comment by sanjay1913** [comment] 2019-04-01 16:10
Unable to open it..
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Xrm.Framework.CI.PowerShell.Scripts, "C:\Users\Public\VSTS\D365XrmConnection\Xrm.Framework.CI\Xrm.Framework.CI.PowerShell.Scripts\Xrm.Framework.CI.PowerShell.Scripts.pssproj"


Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - Xrm.Framework.CI, "C:\Users\Public\VSTS\D365XrmConnection\Xrm.Framework.CI\Xrm.Framework.CI.sln"

**Comment by majakubowski** [comment] 2019-04-02 06:32
@sanjay1913 what connection string do you use? I have a problem with finding the correct connection string to utilise [Client Credentials Flow (ClientId / Secret)](https://oauth.net/2/grant-types/client-credentials/). The only way I managed to achieve this is to create my own AuthHookWrapper ([CrmServiceClient.AuthOverrideHook](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.authoverridehook?view=dynamics-xrmtooling-ce-9)).

**Comment by sanjay1913** [comment] 2019-04-02 08:34
> @sanjay1913 what connection string do you use? I have a problem with finding the correct connection string to utilise [Client Credentials Flow (ClientId / Secret)](https://oauth.net/2/grant-types/client-credentials/). The only way I managed to achieve this is to create my own AuthHookWrapper ([CrmServiceClient.AuthOverrideHook](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.authoverridehook?view=dynamics-xrmtooling-ce-9)).


@majakubowski 
Connection string.
"AuthType=OAuth;Url=https://myCompanyDev.crm4.dynamics.com;Username=User1@CompanyDomain.onmicrosoft.com;Password=[ Password];AppId=ldgd252f-97f9-477d-a4c3-01480a672d6d;RedirectUri=http://localhost/;LoginPrompt=Auto;"

**Comment by sanjay1913** [comment] 2019-04-02 11:00
@WaelHamze and @majakubowski 
Hi Wael,
In online VSTS Agent it downloads Tools Version: 9.0.11 , We are expecting 9.0.12 version according to the fix. When it will be reflecting it

Using Tools Path: C:\DATA\Agent\_work\tools
##[debug]Framework Cache: C:\DATA\Agent\_work\tools\MSCRMBuildTools
Tools Version: 9.0.11
C:\DATA\Agent\_work\tools\MSCRMBuildTools already created
9.0.11 already cached

**Comment by majakubowski** [comment] 2019-04-02 11:43
@sanjay1913 I was convinced that you are trying to use the [client credentials flow](https://oauth.net/2/grant-types/client-credentials/) (without user login/password, dedicated for server to server connections)... here is the instructions how to register such client in Dynamics CRM: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication

You use Username & Password ([password flow](https://oauth.net/2/grant-types/password/))- there is no need to register your own client for this. You could use default, mentioned by me above.

@WaelHamze personally, I do not use CRM Online right now, but I could implement authentication with ClientId/Secret to utilise [Application Users from CRM](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication) instead username/password. What do you think about it?

**Comment by sanjay1913** [comment] 2019-04-02 12:52
> @sanjay1913 I was convinced that you are trying to use the [client credentials flow](https://oauth.net/2/grant-types/client-credentials/) (without user login/password, dedicated for server to server connections)... here is the instructions how to register such client in Dynamics CRM: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication
> 
> You use Username & Password ([password flow](https://oauth.net/2/grant-types/password/))- there is no need to register your own client for this. You could use default, mentioned by me above.
> 
> @WaelHamze personally, I do not use CRM Online right now, but I could implement authentication with ClientId/Secret to utilise [Application Users from CRM](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication) instead username/password. What do you think about it?

@majakubowski  : Do you have powershell for connection using client secretes ?

**Comment by sanjay1913** [comment] 2019-04-02 12:57
@majakubowski  Do you have any power shell connection code using client secrets where can use in automation ?  client credentials flow (without user login/password, dedicated for server to server connections) .. Can you please share the code . We do have client secretes and using .NET .  But powershell to get the conenction in CRM automation.

**Comment by WaelHamze** [comment] 2019-04-02 19:32
> @WaelHamze personally, I do not use CRM Online right now, but I could implement authentication with ClientId/Secret to utilise [Application Users from CRM](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication) instead username/password. What do you think about it?

@majakubowski I presume this would be custom code rather than using the connection string?

@sanjay1913 I'll am doing some regression testing before I package and push this out. I presume you are interested in the Azure DevOps Tasks?

**Comment by majakubowski** [comment] 2019-04-02 20:54
@WaelHamze after a few hours of digging in decompiled Microsoft.Xrm.Tooling.Connector I'm pretty sure that it cannot be done simply by passing connection string to CrmServiceClient constructor.. but maybe @sanjay1913 can change my opinion :) Anyway - from the user's perspective it can looks like using a connection string.. which should be parsed in method XrmConnectionManager.ConnectToCRM.. and then custom code can make connection. Something like that

```
if (connectionstring contains ClientId & Secret)
   make connection with custom auth hook
else
   make standard connection
```
By custom code I mean no more than one or two small classes.

@sanjay1913 do you have a working connection string in which you are using ClientId/Secret without Username/Password... for your custom .net code?

**Comment by Lukis** [comment] 2019-04-03 03:12
The server to server authentication requires a few additional parameters. Check out the sample here: https://github.com/Microsoft/PowerApps-Samples/tree/master/cds/webapi/C%23/SingleTenantS2S . They are in the app.config.

**Comment by sanjay1913** [comment] 2019-04-03 11:33
> @WaelHamze after a few hours of digging in decompiled Microsoft.Xrm.Tooling.Connector I'm pretty sure that it cannot be done simply by passing connection string to CrmServiceClient constructor.. but maybe @sanjay1913 can change my opinion :) Anyway - from the user's perspective it can looks like using a connection string.. which should be parsed in method XrmConnectionManager.ConnectToCRM.. and then custom code can make connection. Something like that
> 
> ```
> if (connectionstring contains ClientId & Secret)
>    make connection with custom auth hook
> else
>    make standard connection
> ```
> By custom code I mean no more than one or two small classes.
> 
> @sanjay1913 do you have a working connection string in which you are using ClientId/Secret without Username/Password... for your custom .net code?

@majakubowski  

Please find below code can be used for connection using Client Secrets, This is common practice to have connection in azure. 
                    AuthenticationContext authContext;
                    const string Resource = "https://dev123.crm4.dynamics.com";

                    // Authroiztion Endpoint
                    string Authority = "https://login.microsoftonline.com/123erdfrtt-ythfhgk-23err-132242fgdghjv/oauth2/authorize";

                    authContext = new AuthenticationContext(Authority, false);
                    ClientCredential clientCredentials = new ClientCredential("weccdffd-bc8c-4274-9a1c-uyrhhggsd87hs", "8qAq/iFD2P+F52yAldZmtivYT3M+ouwD7cbdsjvdybdf=");
                    AuthenticationResult authResult = authContext.AcquireTokenAsync(Resource, clientCredentials).Result;
                    log.Info("authResult" + authResult.AccessToken);

**Comment by sanjay1913** [comment] 2019-04-03 11:34
> > @WaelHamze personally, I do not use CRM Online right now, but I could implement authentication with ClientId/Secret to utilise [Application Users from CRM](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication) instead username/password. What do you think about it?
> 
> @majakubowski I presume this would be custom code rather than using the connection string?
> 
> @sanjay1913 I'll am doing some regression testing before I package and push this out. I presume you are interested in the Azure DevOps Tasks?

     @WaelHamze  , I appreciate your effort on this , I like this DevOps 💯

**Comment by Lukis** [comment] 2019-04-03 13:07
@sanjay1913 - I think the issue for @WaelHamze is how to detect the usage of Sever-to-Server authentication within the connection string. S2S requires a 4th parameter which isn't referenced in any of the existing connection strings utilized within the SDK samples - aka the TenantId. Here's probably what it needs to look like: 
`AuthType=S2S; ClientId=<GUID>; ClientSecret=<KEY>; Url=https://dev123.crm.dynamics.com; TenantId=<GUID>`
I made up the AuthType and a few of the other values, but it might be a good way to detect the S2S and branch into that code.

@WaelHamze - to use the returned token, you'll need to attach it to the SDK's Client Proxy object. We've had some issues initializing it with just the DCRM URL, we've needed to use the GetServiceUrl function to initialize the SDK. I'd be curious if this is still an issue.

    public static IOrganizationService GetOrganizationService(string clientId, string appKey, string crmUrl, string azureAdTenantUrl, string sdkClientVersion)
    {
        ClientCredential clientcred = new ClientCredential(clientId, appKey);
        AuthenticationContext authenticationContext = new AuthenticationContext(azureAdTenantUrl);
        AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(crmUrl, clientcred).Result;
        var requestedToken = authenticationResult.AccessToken;

        var sdkService = new OrganizationWebProxyClient(GetServiceUrl(crmUrl), true);
        sdkService.HeaderToken = requestedToken;
        sdkService.SdkClientVersion = sdkClientVersion;

        return (IOrganizationService)sdkService;
    }

    private static Uri GetServiceUrl(string crmUrl)
    {
        var organizationUrl = new Uri(crmUrl);

        return new System.Uri(organizationUrl +
            @"xrmservices/2011/organization.svc/web"
        );
    }

**Comment by majakubowski** [comment] 2019-04-03 23:01
@Lukis Tenant can be also discovered using [AuthenticationParameters.CreateFromResourceUrlAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationparameters.createfromresourceurlasync?view=azure-dotnet) method
@sanjay1913 you cheat :) your second code is different from the first one.. and in the second code you do not use the connection string.
@WaelHamze please see my PR #205

**Comment by WaelHamze** [comment] 2019-04-04 07:26
By the way the changes that @majakubowski introduced to fix the bug are already in the market place.

@WaelHamze will take a look, although I presume the package deployer which many people use will not use this connection string?

**Comment by majakubowski** [comment] 2019-04-04 08:20
@WaelHamze this connection string (with AuthType = S2S) will be supported only in xrm-ci-framework cmdlets.

**Comment by Lukis** [comment] 2019-04-04 12:26
> @WaelHamze this connection string (with AuthType = S2S) will be supported only in xrm-ci-framework cmdlets.

@majakubowski  Thanks for sharing the AuthenticationParameters.CreateFromResourceUrlAsync link - that is a very nice addition. I"m curious how you found it, was that in the SDK connectivity tools?
Regarding the AuthType=S2S - you could remove the s2s and simply check if there's an ClientId with no UserName attribute and assume the Password is the ClientSecret. However, that makes it feel like a side effect instead of an intended behavior. 

@WaelHamze Our team uses an Application User for all of our CI and custom integration code. This is because it's a non-interactive user account and doesn't cost us a user license. It would be nice to support the connection string across all pipeline steps? How much effort is that and is it something I can help with?

**Comment by WaelHamze** [comment] 2019-04-05 07:07
@Lukis you can connect using username and password and mark the account non-interactive as well which would have the same effort on licensing as well? https://docs.microsoft.com/en-us/dynamics365/customer-engagement/admin/create-users-assign-online-security-roles#create-a-non-interactive-user-account

**Comment by Lukis** [comment] 2019-04-05 10:50
@WaelHamze - that is correct. I also like the ability of the application user to set a long-term expiring password without any additional IT involvement.
Can you think of any negatives of using the application user?

**Comment by majakubowski** [comment] 2019-04-10 06:19
@Lukis some time ago I was trying doing some similar function from scratch (extract STS address from WWW-Authorization header).. but then I found this method on some page with MS docs :)

**Comment by sanjay1913** [comment] 2019-04-17 15:25
@WaelHamze @majakubowski 
I am not able to compile code here #205 after download , missing most of dependencies. Is that possible you to share the compiled binaries for S2S changes.

**Comment by sanjay1913** [comment] 2019-04-18 09:05
Dear @WaelHamze  have you pushed S2S  task's fixes to marketplace?

**Comment by sanjay1913** [comment] 2019-08-16 11:44
Dear @WaelHamze @majakubowski 
Are these changes available in build tasks with which version if not could you pease let me know by when it will be available ? 

Many thanks in advance !!!

**Comment by mlankamp** [comment] 2019-08-30 13:40
I have created a new Pull Request (https://github.com/WaelHamze/xrm-ci-framework/pull/234) where the connection string doesn't contain the S2S parameter. Just specifiy the clientID and Password (leave username empty) and the login will use a S2S login flow.

**Comment by WaelHamze** [comment] 2019-11-09 16:06
I am closing this issue, clientsecret authentication is now available too: https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/use-connection-strings-xrm-tooling-connect

**Closed by WaelHamze** 2019-11-09 16:06 UTC
Labels: enhancement, help wanted
