### ISSUE TITLE
No agent could be found with the following capabilities: powershell, mscrmtools

### ISSUE THREAD

**Issue by veerasekharbathala** [WaelHamze/xrm-ci-framework#217] opened 2019-06-17 13:46 UTC
Hi,

We are using on-premise TFS 2017, agents and Dynamics 365 online instance (v9.1). We installed XRM CI extensions. When i define build pipeline with only 2 steps 1. MS CRM Tool installer 2. MS CRM Ping and queue for new build, i am encountering with below error.

What are tools that i need to install on-premise agent to resolve below error?

**Error Message:**
There are issues with the request or definition that may prevent the build from running:
No agent could be found with the following capabilities: powershell, mscrmtools
Queue the build anyway?

![image](https://user-images.githubusercontent.com/35842369/59609081-b9766c80-90e4-11e9-90d1-2db44c090f5e.png)

Thanks,
Veera

**Comment by WaelHamze** [comment] 2019-06-19 17:38
@veerasekharbathala I think this is a duplicate of: https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues/63

**Closed by WaelHamze** 2019-06-19 17:38 UTC
